### ISSUE TITLE
Hỏi về khóa học về sinh học cho người không học Sinh học?

### ISSUE THREAD

**Issue by thangnh91** [UeenHuynh/MGMA_2024#1]
Chào Thầy ạ, em học IT nên không có biết nhiều về Sinh học, giờ muốn tìm hiểu về Tin sinh, mong thầy gợi ý vài khóa học hay cuốn sách nào mà có kiến thức cần thiết cơ bản để có thể hiểu được các nội dung trong khóa học. Em xin cảm ơn ạ.

**Comment by UeenHuynh** [comment]
Bạn có thể tìm đọc những cuốn sách mà BTC đã có để ở mục reference nha. Mình gợi ý bạn tìm hiểu course này trên coursera nhé https://www.coursera.org/learn/bioinformatics. Trên coursera có nhiều course tham khảo bạn. Cảm ơn bạn.

**Comment by luuloi** [comment]
Em cũng có thể tham khảo thêm tài liệu tóm tắt ngắn ngọn này nhé em!
https://web.stanford.edu/class/cs173/papers/primer.pdf
https://omicstutorials.com/introduction-to-biology-for-bioinformatics/
All the best!
