### ISSUE TITLE
Tạo field trong AWK

### ISSUE THREAD

**Issue by PAXMANXN** [UeenHuynh/MGMA_2024#12]
Ví dụ mình tạo một file abc.txt như thế này:

1, Nguyễn Văn A, Nam
2, Lê Thị B, Nữ
3, Nguyễn Văn C, Nam

Mình làm sao sử dụng awk để awk hiểu là chỉ có 3 columns và in ra $2 là:
Nguyễn Văn A
Lê Thị B
Nguyễn Văn C

Cảm ơn các bạn!

**Comment by huyha1314** [comment]
Ý tưởng là mình sẽ quy định 1 column được tách nhau = dấu ","
Câu lệnh: _awk -F"," '{print $2}' abc.txt_
-F sẽ quy định 1 cột được tách nhau bởi gì
{print $2} sẽ là in cột 2 của mỗi dòng mà awk quét qua
