### ISSUE TITLE
bài tập Bash Scripting

### ISSUE THREAD

**Issue by VanChungCC** [UeenHuynh/MGMA_2024#13]
Các anh chị cho em hỏi sao em download với lệnh như trong bài tập ghi nhưng tải không được ạ (em đã cài curl).
Em copy lệnh trên file để đưa vào nhưng không được ạ.

**Comment by huyha1314** [comment]
Khi copy paste 3 lệnh này 1 lúc thì file sẽ được down ở thư mục homework. Một lưu ý nữa khi đã nhập và kích hoạt 3 câu lệnh cùng 1 lúc thì đợi 5s và nhấn crt C để hủy bỏ thao tác vì curl đã down file xong nhưng không tự động kết thúc câu lệnh

mkdir ./homework

curl -o ./homework/fa1.txt https://drive.usercontent.google.com/download?id=1RvsIx3_qGI_znCAWHDycHKfhUQxm5U6j&export=download&authuser=0

curl -o ./homework/fa2.txt https://drive.usercontent.google.com/download?id=1znAljOXBLbeq4qt0asce185mzKkPgmxv&export=download&authuser=0

![Screenshot from 2024-05-28 21-27-19](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/cd990128-2453-4dcf-90ef-a890d4507f0d)

Bạn có thể sử dụng lệnh _ls ./homework_ để xem có file đã down chưa? 
![Screenshot from 2024-05-28 21-28-59](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/803a399e-f282-46b8-927d-deff09440432)

**Comment by huyha1314** [comment]
Hoặc bạn có thể down bằng click chuột bằng cách nhấp vào đường link

**Comment by VanChungCC** [comment]
dạ em đã thử ls rồi mà không ra, để em thử dùng 3 lệnh cùng lúc xem sao

**Comment by VanChungCC** [comment]
dạ em copy 3 lệnh cùng 1 lúc thì được rồi ạ, nhưng cho em hỏi có sự khác nhau nào giữa copy 3 lệnh cùng lúc và riêng từng lệnh ạ.

**Comment by huyha1314** [comment]
-Lệnh đầu để tạo thư mục homework 
-Lệnh 2 và 3 để down file về thư mục homework nên phải có thư mục homework thì mới down đc file.

**Comment by huyha1314** [comment]
Thế bạn down thủ công bằng cách click chuột vào link đi cho gọn tại mình thử nó cũng trục trặc chứ kh mượt lắm

**Comment by VanChungCC** [comment]
em chạy lệnh đầu tiên tạo ra thư mục rồi, sau đó down tệp thứ nhất thì không được,

**Comment by VanChungCC** [comment]
dạ, em cam ơn ạ.

**Comment by huyha1314** [comment]
bạn thử screenshot xem?

**Comment by huyha1314** [comment]
mkdir ./homework

curl -o ./homework/fa1.txt https://drive.usercontent.google.com/download?id=1RvsIx3_qGI_znCAWHDycHKfhUQxm5U6j

curl -o ./homework/fa2.txt https://drive.usercontent.google.com/download?id=1znAljOXBLbeq4qt0asce185mzKkPgmxv

Bạn thử 3 câu lệnh này lại xem mình mới fix lại URL rồi

**Comment by VanChungCC** [comment]
dạ em tải được rồi ạ. thấy bị lỗi ở chỗ nào rồi ạ, lúc em copy xong paste lại thì có ký tự mới xuất hiện, em bỏ nó thì nó được rồi ạ. Em cảm ơn ạ.
