### ISSUE TITLE
Không thể tải file fasta trong bài tập linux basic commnad 2

### ISSUE THREAD

**Issue by bichcamtran** [UeenHuynh/MGMA_2024#15]
Mình sử dụng lệnh wget và copy đường dẫn theo hướng dẫn nhưng trả kết quả là 404 not found, cho mình hỏi đã sai bước nào
![Uploading 171705427110394760032727068901.jpg…]()

**Comment by Khaingyn** [comment]
Chị xem xem phải lỗi này không nha: https://github.com/UeenHuynh/MGMA_2024/issues/5#issue-2315716445

**Comment by bichcamtran** [comment]
Mình làm theo hướng dẫn của bạn rồi nhưng vẫn ko được.
Mình có check lại file data trên github thì hình như đường dẫn thấy đổi phải ko bạn.
Có lệnh nào giúp mình load file đã tải về mà ko thông qua đường dẫn ko. Mình cảm ơn nha

**Comment by Khaingyn** [comment]
Chị gửi lại ảnh chụp màn hình em xem với, không biết phải vấn đề bên em không nhưng ảnh trên chị gửi nó không load được. 
Em vừa thử lại, em vẫn tải được:
![sp](https://github.com/UeenHuynh/MGMA_2024/assets/147164871/20e5b9f7-e29e-4085-a8ce-ae6ebb787a01)

**Comment by Khaingyn** [comment]
https://github.com/UeenHuynh/MGMA_2024/assets/147164871/4c06c41b-662c-4329-b8e7-3eb32b31291a

Video em quay màn hình lại

**Comment by bichcamtran** [comment]
Mình cài máy ảo, nó lag khi chuyển sang web github nên mình tạm chụp bằng đth
![17170594536127982826341752849161](https://github.com/UeenHuynh/MGMA_2024/assets/170500826/5f2ee558-f8b5-4995-8151-2d792e3ff37f)

**Comment by Khaingyn** [comment]
> Mình cài máy ảo, nó lag khi chuyển sang web github nên mình tạm chụp bằng đth ![17170594536127982826341752849161](https://private-user-images.githubusercontent.com/170500826/335113985-5f2ee558-f8b5-4995-8151-2d792e3ff37f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjI5ODksIm5iZiI6MTcxNzA2MjY4OSwicGF0aCI6Ii8xNzA1MDA4MjYvMzM1MTEzOTg1LTVmMmVlNTU4LWY4YjUtNDk5NS04MTUxLTJkNzkyZTNmZjM3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwOTUxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjNkNGUzYWE2NjNhNjNmMGRlNzg3ODY4YzZmMjJjY2FlNDMyZjM5NjhlZTIxY2YwOTI2OTQ3ZTM5MmI2NWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2zZ9vGDQls2FaGcM6qCU0zYF_t8UrKv91L4TWlRUzlc)

như chị chụp thì em thấy có 1 dấu ngã ở cuối link, chị kiểm tra lại xem, link em ko có dấu ngã đó

**Comment by Khaingyn** [comment]
Chị tải được với wget rồi thì comment cho em biết nha

**Comment by bichcamtran** [comment]
Máy cài Ubuntu ảo hiện tại đang gặp lỗi nên ko có cách nào làm tiếp. Để khi nào được mình cập nhật nha.

**Comment by Khaingyn** [comment]
> Máy cài Ubuntu ảo hiện tại đang gặp lỗi nên ko có cách nào làm tiếp. Để khi nào được mình cập nhật nha.

Chị có thể dùng Ubuntu trên WSL cũng được lắm
