### ISSUE TITLE
Các bạn cho mình hỏi command grep -c "^>" tên file. c - option ở đây có nghĩa là gì? Cám ơn 

### ISSUE THREAD

**Issue by ThaoThuMai** [UeenHuynh/MGMA_2024#16]

**Comment by Khaingyn** [comment]
nếu ko dùng option c, thì grep sẽ in ra tất cả các hàng bắt đầu bằng ký tự >, dùng option c thì grep sẽ in ra số hàng bắt đầu bằng ký tự > chứ ko in ra tất cả các hàng nữa. 
Về việc xem hướng dẫn dùng lệnh cũng như tên đầy đủ và ý nghĩa của các option của mỗi lệnh, bạn chạy dòng lệnh:
tên_lệnh --help 
hoặc:
man tên_lệnh
như trong bài "Ubuntu và basic Linux commands part 1" đã trình bày. Ngoài ra nếu xem trong đó chưa hiểu thì mình có thể google thêm hoặc hỏi chat gpt.

**Comment by huyha1314** [comment]
Thông tin đến bạn, mình có thể sử dụng chatGPT hoặc gemini của google để tìm hiểu những cái lệnh cơ bản này và tiết kiệm thời gian hơn ví dụ ở bên dưới. Hỏi grep -c trong ubuntu có nghĩa gì và cho ví dụ.
![image](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/99dd62e7-a15e-4b25-9525-e9bc0f01be9e)
