### ISSUE TITLE
Hỏi về homework2 của lesson 3

### ISSUE THREAD

**Issue by HeCTorTRoNg** [UeenHuynh/MGMA_2024#17]
Sau đây là commands của script em dựa trên mục homework answer trên github:

![image](https://github.com/UeenHuynh/MGMA_2024/assets/170555937/af0bf5c8-2822-4fa8-a4da-bb60f064a8e6)

Tuy nhiên trên terminal chỉ cho ra một dòng thay vì nhiều dòng như hình terminal trong file giảng: 

![image](https://github.com/UeenHuynh/MGMA_2024/assets/170555937/07ffcfab-1c08-429d-9de1-54516c4eed58)

Cho em xin phép hỏi là liệu phần bash script của em đã bị dính lỗi gì? Và em cần làm gì để sửa lỗi ấy.

Em cảm ơn

**Comment by huyha1314** [comment]
Chào bạn, ở dòng 2 bạn dùng 'ls ./home/practice'
Thì đối với bash script lệnh này nó kh hiểu được đường dẫn tương đối là dấu ./ nó chỉ hiểu đường đường dẫn tuyệt đối nên bạn thử đổi tất cả đường dẫn tương đối ./home/practice/$name thành /home/hectortrong/home/practice/$name sẽ thành công. 

Nếu bạn còn lỗi hay thắc mắc gì có thể trao đổi thêm

**Comment by VanChungCC** [comment]
Dạ em chào anh/chị ạ, em cũng muốn hỏi bài tập này ạ
Lệnh em viết  nhưng không chạy được ạ
![Screenshot from 2024-06-05 16-32-55](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/da568a86-b771-414c-a766-2e503c77ac85)
![Screenshot from 2024-06-05 16-25-04](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/e31897f7-17e7-4378-8f21-08e9f8926edf)

**Comment by VanChungCC** [comment]
và nếu được thì giải thích giúp em cái lệnh trong phần if với ạ, tại lúc đầu em nghĩ là phải dựa vào phần này đề phân biệt file và directory, là dựa vào chữ cái đầu tiên ở cột đầu tiên để phân biệt ạ
![Screenshot from 2024-06-05 16-41-10](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/9e927756-586c-4a77-b1e3-0551a54cb606)

**Comment by huyha1314** [comment]
À ok, bạn xem lại dấu huyền (``)-là thực hiện câu lệnh và lưu trữ kết quả khác dấu nháy đơn(' ')-là quy định ở giữ nó là text. Bạn thử đổi lại nha.
Ở dòng số 2 @VanChungCC @HeCTorTRoNg 
LƯU Ý khi copy paste nó hay bị lỗi lắm nên check lại mấy dấu câu.

Hoặc nếu không được nữa thì bạn bỏ những câu lệnh ở giữa 2 dấu `` vào giữa $() nó có tác dụng tương tự

**Comment by VanChungCC** [comment]
Dạ
