### ISSUE TITLE
Hỏi về homework2 Lecture2 (Bash Script)

### ISSUE THREAD

**Issue by DrYong1996** [UeenHuynh/MGMA_2024#18]
Đáp án của bài dùng lệnh cat ở phía trước nhưng khi mình đổi sang lệnh này thì lại hiện như thế này. Thầy và các bạn giúp mình với ạ. Xin cảm ơn.

<img width="451" alt="Picture1" src="https://github.com/UeenHuynh/MGMA_2024/assets/170739225/96c39024-d802-4a36-ba54-06a90404749a">

**Comment by huyha1314** [comment]
Chào bạn, vấn đề của bạn
1. Là dòng 1 của bạn kh có #!/bin/bash nên ubuntu kh hiểu đây là ngôn ngữ lập trình bash
2. File bạn đặt kh phải là đuôi .sh
Chỉ cần fix 1 trong 2 vấn đề trên là chạy đc
Lưu ý bạn có thể sử dụng cat -n để hiện số dòng tiện cho việc kiểm tra 

3. File script của bạn viết ở dòng 5 điều kiện biến bị viết sai.($a và $b)  $a1 và $b1 mới đúng

**Comment by DrYong1996** [comment]
Mình đã fix cả 3 lỗi nhưng vẫn không chạy được @huyha1314 
<img width="451" alt="Picture1" src="https://github.com/UeenHuynh/MGMA_2024/assets/170739225/21052581-6cfa-4a3e-b6a3-1898fdd1f348">

**Comment by huyha1314** [comment]
À ok, bạn xem lại dấu huyền (``)-là thực hiện câu lệnh và lưu trữ kết quả khác dấu nháy đơn(' ')-là quy định ở giữ nó là text. Bạn thử đổi lại nha. 
LƯU Ý khi copy paste nó hay bị lỗi lắm nên check lại mấy dấu câu.

Hoặc nếu kh được nữa thì bạn bỏ những câu lệnh ở giữa 2 dấu `` vào giữa $() nó có tác dụng tương tự

**Comment by DrYong1996** [comment]
Cảm ơn bạn nhé
