### ISSUE TITLE
Hỏi về Homework Lecture3 (BashScript)

### ISSUE THREAD

**Issue by DrYong1996** [UeenHuynh/MGMA_2024#19]
awk '/translation/{while(i=1){print $0;getline; if ($1=="XX"){break} } }' U31362.1.gb|awk '{print $2}'|tr -d '/translation="'
- Thầy và các bạn Tutor có thể giải thích kĩ hơn về việc sử dụng các câu lệnh 
while(i=1)
print $0;getline
Xin chân thành cảm ơn.

**Comment by huyha1314** [comment]
![image](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/30c7afac-32ae-4ba4-85e5-44c1f4547f22)
Đây là cấu trúc dữ liệu trong file và mình muốn lấy trình tự acid amin trên đây
Ý tưởng là
1.mình sẽ bắt đầu lấy kí tự từ chữ translation 
2. vì mình không biết sẽ lấy bao nhiêu dòng với đoạn acid amin dài bao nhiêu mình sẽ có một vòng lập vô tận với điều kiện luôn đúng là while i=1
3. Thì mình sẽ in ra cả dòng đó và xuống 1 dòng tiếp tục in cho đến khi chạm đến kí hiệu XX ở cấu trúc dữ liệu thì sẽ dừng lại 
4. sau đó mình sẽ xử lý cắt bỏ chữ FT và translation không cần

while (i=1) - 1 vòng lập vô tận với điều kiện luôn đúng nhằm in hết tất cả các dòng aa mà mình không biết file đó là bao nhiêu dòng
print $0; getline - in cả dòng đó ra và xuống 1 dòng tiếp tục vòng lập
break - điều kiện để kết thúc vòng lập là khi nó gặp chữ XX nghĩa là đã hết trình tự aa

**Comment by DrYong1996** [comment]
Cảm ơn bạn nhé @huyha1314
