### ISSUE TITLE
Lỗi cài Ubuntu này là gì vậy các bạn?

### ISSUE THREAD

**Issue by PAXMANXN** [UeenHuynh/MGMA_2024#2]
<img width="595" alt="image" src="https://github.com/UeenHuynh/MGMA_2024/assets/170701865/db327ada-2488-4439-b85d-50f5ef1f5c6a">

**Comment by huyha1314** [comment]
https://www.youtube.com/watch?v=1kFFwknneD8&t=499s

Bạn nên xem thêm ở đây để nắm rõ hơn chi tiết cách cài đặt nha.

**Comment by Khaingyn** [comment]
Bạn thử cách khác. Bạn vào Microsoft Store, tìm Ubuntu rồi click "Get" theo methods 1 xem được không:
https://canonical-ubuntu-wsl.readthedocs-hosted.com/en/latest/guides/install-ubuntu-wsl2/

**Comment by Khaingyn** [comment]
Nếu bạn xử lý theo cách khác và thành công, bạn comment lại hướng mà bạn đã xử lý trên này cho mọi người biết biết nha! Để mình đóng issue này, để biết rằng vấn đề đã được giải quyết.

**Comment by PAXMANXN** [comment]
> Nếu bạn xử lý theo cách khác và thành công, bạn comment lại hướng mà bạn đã xử lý trên này cho mọi người biết biết nha! Để mình đóng issue này, để biết rằng vấn đề đã được giải quyết.



> Nếu bạn xử lý theo cách khác và thành công, bạn comment lại hướng mà bạn đã xử lý trên này cho mọi người biết biết nha! Để mình đóng issue này, để biết rằng vấn đề đã được giải quyết.

Tui làm theo cách vào MS store down Ubuntu về, nên không còn bị lổi nữa. Thanks các bạn
