### ISSUE TITLE
Hỏi về Homework Lecture 5 (R Coding) 

### ISSUE THREAD

**Issue by ONT16S** [UeenHuynh/MGMA_2024#21]
Trong phần bài tập câu 2 có so sánh 'setora' và 'versicolor', nhưng bảng data chỉ có 'setora' nên mình không biết là sẽ tự giả định thêm vào file cvs hay là do ghi nhầmtên. Mình xin cảm ơn.
![image](https://github.com/UeenHuynh/MGMA_2024/assets/171407091/05ad7d67-ab9e-49db-a9d4-75f6359eee51)

**Comment by quyho0944** [comment]
cái đó là 1 phần của bảng đó bạn 
```{r}
str(iris)
View(iris)
```
bạn dùng lệnh này để xem thêm
