### ISSUE TITLE
trục trặc khi tải book về #question

### ISSUE THREAD

**Issue by PLe0111** [UeenHuynh/MGMA_2024#22]
em vào từng mục của 3 mục nhỏ R book, bioinformatics_linux, metagenomics nhưng tất cả các mục đều hiện là "Unable to render code block" và không thấy link raw file để tải về ạ?
Mong nhận được phản hồi hướng dẫn download ạ.
Em cảm ơn ạ.

**Comment by PAXMANXN** [comment]
Mình có cách nào download nguyên các folder lecture từ Githut về máy không các bạn?

**Comment by huyha1314** [comment]
Issue #7 @PAXMANXN 
Có hướng dẫn down nguyên folder 
Hoặc bạn có thể sử dụng git để clone folder từ github về máy. Vào youtube gõ git clone folder tutorial để thêm thông tin chi tiết
