### ISSUE TITLE
Alignment khi độ dài trình tự không đều nhau?

### ISSUE THREAD

**Issue by PAXMANXN** [UeenHuynh/MGMA_2024#23]
Hi các bạn, các trình tự khác nhau về chiều dài DNA thì có làm alginment theo các syntax dưới không?
<img width="283" alt="image" src="https://github.com/UeenHuynh/MGMA_2024/assets/170701865/8140d2c1-0fa4-43c5-8f7b-c7fdb47e78e7">

**Comment by ducminhnguyenle** [comment]
Xin chào bạn,
### Với các trinh tự có chiều dài khác nhau thì việc làm alignment vẫn có thể thực hiện được tùy theo phương pháp lựa chọn, ví dụ:
- Với phương pháp Multiple Sequence Alignment (MSA), hoàn toàn có thể align các sequence có chiều dài khác nhau. Một số thuật toán tham khảo như Clustal Omega, MAFFT, MUSCLE, T-Coffee, v.v...
- Với phương pháp Pairwise Sequence Alignment (PSA):
  1.  Hamming distance: yêu cầu các đoạn sequence cùng chiều dài, tuy nhiên nếu các trình tự đã được align với các gap thì vẫn có thể tính toán hamming distance
  2.  Striped Smith Waterman: có thể pairwise alignment các cặp trình tự có chiều dài khác nhau

### A toy example using skbio package with StripedSmithWaterman algorithm
```python
from skbio.alignment import local_pairwise_align_ssw
from skbio.alignment import StripedSmithWaterman
from skbio import TabularMSA, DNA
# StripedSmithWaterman local pairwise alignment
alignment, score, start_end_pos = local_pairwise_align_ssw(
    DNA("ACTAAGGCTCTCTACCCCTCTCAGAGA"),
    DNA("ACTAAGGCTCCTAACCCCCTTTTCTCAGA")
)
print(alignment)
print(score)
print(start_end_pos)
print("")
# SSW object
query = StripedSmithWaterman("ACTAAGGCTCTCTACCCCTCTCAGAGA")
alignment = query("AAAAAACTCTCTAAACTCACTAAGGCTCTCTACCCCTCTTCAGAGAAGTCGA")
print(f"Optimal alignment score: {alignment.optimal_alignment_score}")
print(f"Cigar string:    {alignment.cigar}")
print(f"Query sequence:  {alignment.aligned_query_sequence}")
print(f"Target sequence: {alignment.aligned_target_sequence}")
```
### Output ví dụ
```text
TabularMSA[DNA]
------------------------------
Stats:
    sequence count: 2
    position count: 30
------------------------------
ACTAAGGCTCTCT-ACCCC----TCTCAGA
ACTAAGGCTC-CTAACCCCCTTTTCTCAGA
27
[(0, 24), (0, 28)]

Optimal alignment score: 49
Cigar string:    20M1D7M
Query sequence:  ACTAAGGCTCTCTACCCCTC-TCAGAGA
Target sequence: ACTAAGGCTCTCTACCCCTCTTCAGAGA
```
### Reference
> 1. Zhao, Mengyao, Wan-Ping Lee, Erik P. Garrison, & Gabor T. Marth. “SSW Library: An SIMD Smith-Waterman C/C++ Library for Applications”. PLOS ONE (2013). Web. 11 July 2014. http://www.plosone.org/article/info:doi/10.1371/journal.pone.0082138
> 2. scikit-bio/scikit-bio: scikit-bio, Version 0.6.0 [10.5281/zenodo.10888788](https://doi.org/10.5281/zenodo.10888788)

**Comment by PAXMANXN** [comment]
Cảm ơn bạn Đức Minh rất nhiều !

**Comment by ducminhnguyenle** [comment]
Nếu bạn không có thắc mắc gì thêm, minh sẽ close issue này. Nếu bất kỳ anh/chị/bạn nào có thắc mắc có thể thoải mái open issue này lại. Mình cám ơn.
