### ISSUE TITLE
Lỗi cái packages("rentrez")!

### ISSUE THREAD

**Issue by PAXMANXN** [UeenHuynh/MGMA_2024#25]
Hi các bạn, nhờ các bạn xem cái lỗi như hình dưới khi cài packages("rentrez") trong R giùm với.
<img width="389" alt="image" src="https://github.com/UeenHuynh/MGMA_2024/assets/170701865/fd98363f-6b03-4736-80b6-af3f8684f57a">

**Comment by huyha1314** [comment]
![image](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/88de333a-b49d-4b51-ad27-ee8a09ab747e)
Thường thì mình sẽ chạy R trên rstudio và khi chạy rstudio trên ubuntu thường sẽ gặp lỗi thiếu các ứng dụng (dependencies) liên quan.

1. Bạn có thể copy lỗi mà rstudio hoặc R-base trả về lên chat GPT có thể đưa cách sửa. 
2. Thường khi cài packages sẽ sử dung lệnh - "install.packages("rentrez", dependencies = TRUE)" để R tự động cài các packages liên quan
3. Nếu bạn chạy rstudio trên window theo kinh nghiệm mình thì sẽ ít gặp lỗi cài packages hơn
![image](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/c45db047-0bb7-4cfe-a342-b2a0a88e3392)
