### ISSUE TITLE
Hỏi về cách Dowmoad File = Wget

### ISSUE THREAD

**Issue by DrYong1996** [UeenHuynh/MGMA_2024#3]
- Mình có Dowload file bài tập SRR25653406.fasta.tar.gz bằng Linux như hướng dẫn. Tuy nhiên, khi chạy tập lệnh giải nén thì xuất hiện lỗi phát sinh như thế này khi chạy lệnh: tar -xvf SRR25653406.fasta.tar.gz
gzip: stdin: not in gzip format tar:
Child returned status 1
tar: Error is not recoverable: exiting
- Mình có tìm hiểu do định dạng file tải về không phải gzip. 
- Mình thử Dowload thủ công trực tiếp trên Website thì lại dùng lệnh giải nén được
--> Các thầy, các bạn có thể hỗ trợ mình các dowload trực tiếp mà không bị lỗi trên không ạ?
Cảm ơn nhiều

**Comment by DrYong1996** [comment]
[10.1016-j.ccell.2018.01.003Figure1.pptx](https://github.com/UeenHuynh/MGMA_2024/files/15435665/10.1016-j.ccell.2018.01.003Figure1.pptx)

**Comment by DrYong1996** [comment]
<img width="1440" alt="Ảnh màn hình 2024-05-24 lúc 15 49 39" src="https://github.com/UeenHuynh/MGMA_2024/assets/170739225/3a007eec-7a7f-465a-baca-0386d5a2a6fb">

**Comment by Khaingyn** [comment]
Bạn kiểm tra lại xem mình download thành công chưa nha, dùng ls để xem đã có file chưa sau khi dùng wget tải file. Bên mình không thấy có vấn đề gì.
![Screenshot 2024-05-24 222259](https://github.com/UeenHuynh/MGMA_2024/assets/147164871/cb26a81e-a17d-40c1-af57-aa647624f460)

**Comment by tuanna199** [comment]
Em nghĩ cái này là do lỗi của file SRR25653406.fasta.tar.gz, như anh mô tả thì em nghĩ anh/chị có thể kiểm tra xem đã download đúng file chưa, có thể do lỗi của link khi wget ạ.

**Comment by Khaingyn** [comment]
Có thể anh/chị mắc phải lỗi này khi tải file, em đã đăng lên thành 1 issue:
https://github.com/UeenHuynh/MGMA_2024/issues/5#issue-2315716445

**Comment by DrYong1996** [comment]
Okey bạn. Cảm ơn mọi người nhé.
