### ISSUE TITLE
Bài tập buổi 9

### ISSUE THREAD

**Issue by VanChungCC** [UeenHuynh/MGMA_2024#33]
Có anh chị nào giúp em với ạ, với lại ở phần tải 
# Genotype: CalB_546_1
wget -P ./raw/ ftp.sra.ebi.ac.uk/vol1/fastq/SRR287/067/SRR28714667/SRR28714677_{1,2}.fastq.gz
thì báo lỗi ạ, có anh chị nào tải được phần này không ạ.

**Comment by VanChungCC** [comment]
Ở phần 3 
3. Prepare reference genome: Genome assembly ASM19595v2
thì ờ em bị lỗi này nữa ạ
![Screenshot from 2024-06-20 06-12-13](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/2047d536-cb2b-4383-a84e-520ea8791d66)

**Comment by ducminhnguyenle** [comment]
- Error của bạn là `Check your paths and file permissions and try again`
- Bạn nên kiểm tra lại đường dẫn tới các file cần thiết cũng như tools cần để chạy. Và đồng thời bạn nên kiểm tra quyền sử dụng của file.
Thank you

**Comment by VanChungCC** [comment]
cho em hỏi là dùng tool gì đề chạy ạ

**Comment by VanChungCC** [comment]
dạ anh ơi em thấy đường dẫn bị thiếu ạ, nên em làm không được, 
nucmer \
    -p "./ref/masked/reference" \ 
cái này bị thiếu ạ 
-p "./ref/ASM19595v2/masked/reference" \  cái này mới chạy được ạ.

**Comment by ducminhnguyenle** [comment]
Cái path `-p "ref/masked/reference"` là output của tool nucmer ở trên. Cụ thể nó sẽ là tên file prefix được thêm vào khi kết quả được tạo ra. Bạn chỉ cần tạo một folder nào đó mình muốn chứa kết quả thay vào chỗ `-p` đó là sẽ được.

**Comment by VanChungCC** [comment]
dạ em hiểu rồi ạ,
rồi anh ơi tới lỗi này nữa ạ
![Screenshot from 2024-06-20 22-16-59](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/64cba6dd-b5de-4d75-b277-62a6ecb2243e)
anh xem thử có bị sai câu lệnh không ạ.

**Comment by ducminhnguyenle** [comment]
Em chưa cài tool tương tứng nên báo lỗi `command gatk not found`. Để cài tools như thế nào thì bạn nên xem hướng dẫn ở đây.
- [Raw Data Processing and Alignment/Mapping](https://www.youtube.com/watch?v=ZqmkzgHgUuM&list=PLXtgXP89Tyn92OdScNIYBUBI8DNCFCCN4&index=4)
- [Tutorials](https://drive.google.com/drive/folders/1YtAtUe0qIXOHe43qW3eAwH-Wo6jmitkh)

**Comment by VanChungCC** [comment]
Dạ em cảm ơn anh để em xem lại ạ. Chắc em còn phải hỏi anh ở bài tập này nhiều vì nó mới với em quá ạ.

**Comment by VanChungCC** [comment]
anh ơi em đang cài đặt tool GATK theo như hướng dẫn trong phần tutorials anh chỉ ở trên,
các bước như # Install git-lfs # Set up java version 17 ## Download java 17 ## Switch to java 17
## Type selection number 1,2,3,... that correspond to Java 17 and press Enter  thì em đã làm hết rồi nhưng ở bước này
# Build gatk
cd gatk/
sudo ./gradlew bundle 
thì em bị lỗi này ạ
![Screenshot from 2024-06-21 22-27-17](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/7449bf47-d26e-4078-9024-ec10901d96d9)
em thấy nó báo lỗi này là đường dẫn không đúng, em tìm cách cách để tìm được dẫn như find hay located đề tìm gatk nhưng không được ạ, anh có thế giúp em vượt qua bước này với ạ.

**Comment by ducminhnguyenle** [comment]
- Vậy có thể em chưa install được. chưa có folder nào tên gatk nên em không thể cd vào được (`cd: gatk/: No such file or directory`) .
- `./gradlew: command not found` là cũng chưa có cài đặt tool này, em tham khảo https://stackoverflow.com/questions/41700798/error-message-gradlew-command-not-found

**Comment by VanChungCC** [comment]
dạ em đang làm lại từ đầu thử ạ, cảm ơn anh ạ.

**Comment by VanChungCC** [comment]
em đã cài được tool gatk, nhưng lúc chạy lệnh gatk vẫn báo lỗi ạ, cho em hỏi mình phải làm sao ạ.(lúc cài tool gatk thì không bị vấn đề gì ạ)
![Screenshot from 2024-06-22 16-39-12](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/3415d66f-9666-4548-b18e-5b3cfe4deca2)
![Screenshot from 2024-06-22 16-38-37](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/d4e3268d-06cc-47b4-a921-6078843041aa)
![Screenshot from 2024-06-22 17-23-00](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/5bac4160-7d9d-4116-aad7-595e490868f6)

**Comment by ducminhnguyenle** [comment]
Em check lại cái path cũng như xem trong folder đó có file script gatk đã set quyền thực thi (execute) chưa

**Comment by VanChungCC** [comment]
![Screenshot from 2024-06-22 22-20-27](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/20ee0686-57d3-4d2a-9b0e-9c53b67af833)
![Screenshot from 2024-06-22 22-19-18](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/f08a9da5-542d-4708-8e5a-d733cd6d930c)
dạ ý anh là cái này đúng không ạ, em thấy nó có quyền thực thi rồi ạ.

**Comment by ducminhnguyenle** [comment]
Vậy em thử `cd` vào trong folder đó và chạy thử `./gatk --version`

**Comment by VanChungCC** [comment]
![Screenshot from 2024-06-22 23-04-06](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/ba84a8f2-4626-49e5-82f8-7d6cd7d7981e)
dạ em đã vào thư mục tools để chạy lệnh như anh nói nhưng nó báo như trong hình em chụp, tiếp theo đó em vào trong thư mục gatk để chạy lệnh anh nói thì nó hiện ra lỗi như hình ạ.
dạ thêm cái này nữa anh ơi, em mới phát hiển ra là sau khi em cài mấy cái tool để làm bài tập 9 này thì cái terminal của em lúc mới mở lên nó không được như bình thường ạ, đầu tiên lúc mở terminal ra là nó là một cái bảng trống trơn luôn, bình thường là nó có dòng này chungpc@chungpc:~$ , sau đó em để im đó tầm 30s sau thì nó ra những dòng lệnh chạy vô hạn, tình trạng như hình ạ, để bỏ cái tình trạng đó em phải ấn phím ctrl +C đề dừng ạ, cho em hỏi là lúc em tải mấy tool trên thì có nhập vào các đường dẫn export, em không biết có bị sai chỗ nào không nữa, em chỉ thêm vào dòng export ở cuối như hướng dẫn, có 1 cái thắc mắc là sau mỗi lệnh export đó thì sẽ có lệnh source ~/.bashrc, thì em đã để chỉ 1 lệnh này ở cuối thôi không biết nó có ảnh hưởng gì không. Em thử bỏ hết lệnh mà em thêm vào từ lúc cài các tool thì terminal mở lênh như bình thường ạ. Em không biết như anh đã cài hết những tool đó rồi thì lúc mở terminal lên có bị như em không ạ.
![Screenshot from 2024-06-22 23-09-27](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/0a1676b4-e23c-48bf-8e82-3789217e9f0d)
![Screenshot from 2024-06-22 23-08-46](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/43acac2e-b282-4d04-a90a-483158ddc916)
![Screenshot from 2024-06-22 17-23-00](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/8e98e91e-761d-4d9d-9731-624000a7806d)

**Comment by ducminhnguyenle** [comment]
Em phải đi vào trong folder gatk, rồi xem có cái script cùng tên không và chạy thử.
Lệnh `source ~/.bashrc` chạy riêng ở ngoài, không có thêm vào file `.bashrc`

**Comment by VanChungCC** [comment]
dạ em cd vào gatk rồi ạ, rồi dùng lệnh ./gatk --version  thì kết quả ra như hình ạ
![Screenshot from 2024-06-23 13-39-42](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/0c08d237-767f-40b2-83b3-361efb2c9fa0)

**Comment by lucianhu** [comment]
Chào em, đây là lỗi do em chưa cài python vào máy. Như chị đã comments ở 1 issues khác, em chịu khó tự tìm câu trả lời trước, như search google nè, dùng chatGPT hay germini. Các video Youtube bằng tiếng Anh cũng có rất rất nhiều videos hướng dẫn cài. Mình tự tìm câu trả lời thì sẽ giúp mình học và đào sâu thêm kiến thức. Ngoài ra, em tìm hiểu thêm conda để cài các phần mềm bioinformatic tools dễ hơn
https://www.youtube.com/watch?v=2bXGm0ZnJ38&t=315s

**Comment by VanChungCC** [comment]
dạ em cảm ơn chị ạ, em có dùng chatGPT đề làm hỏi nhưng nó không giải quyết được vấn đề mà đưa em đến vấn đề mới nữa ,nên em lênh trên này để hỏi ở bước  khi xảy ra vấn đề đầu tiên xem có cách giải quyết nào khác không ạ, có nhiều vấn đề được giải quyết sau khi em hỏi nên em hi vọng lần này nó cũng vậy ạ. Em có tải Python và làm như chatGPT hướng dẫn nên  như nó nói nhưng nó lại có vấn đề mới nữa. Em sẽ xem clip chị share và cố gắng tự tìm hướng giải quyết ạ, sau cùng em cảm ơn chị lần nữa ạ.

**Comment by lucianhu** [comment]
chatGPT trả lời khá tốt các câu hỏi cơ bản. Quan trọng là em phải đưa cho nó 1 câu hỏi đầy đủ và nêu đủ hoàn cảnh. Nếu em chỉ copy mỗi cái lỗi thì nó sẽ không hiểu em làm cái gì cả. Em phải đưa toàn bộ script cho nó, em đã làm bước gì và nó bị lỗi gì abc,..thì nó mới có thể trả lời chính xác cho em được.

**Comment by VanChungCC** [comment]
dạ, đúng là trước đó em chỉ hỏi chatGPT cái lỗi em đang gặp thôi ạ, để em làm như cách chị là đưa nó nhiều thông tin hơn thử ạ. Em cảm ơn chị.
