### ISSUE TITLE
bài tập 9 phần Calling variants and visualization of variants (VCF)

### ISSUE THREAD

**Issue by VanChungCC** [UeenHuynh/MGMA_2024#36]
dạ cho em hỏi là em đã cài ubuntu rồi thì có phải cài condacolab không ạ, tại em nghe anh giảng bài thì chỉ cái đó chỉ dành cho những anh chị không cài ubuntu. Nếu em đã cài hệ điều hành ubuntu thì phải cài tool gì để làm phần này ạ.

**Comment by quyhoyasuo** [comment]
Xin chào bạn, cảm ơn bạn vì một câu hỏi rất hay, mình xin trả lời câu hỏi của bạn như sau. Nếu bạn không dùng colab mà dùng máy local thì có thể tải miniconda, cái này cũng sẽ giúp bạn có thể cài conda trên máy local của mình, condacolab chỉ là 1 phiên bản được phát triển để tương thích cho người dùng colab thôi nên nếu không dùng thì bạn có thể dùng miniconda để thay thế. 
Link install: [miniconda](https://educe-ubc.github.io/conda.html)

**Comment by VanChungCC** [comment]
em đã làm tới bước này để cài đặt miniconda tuy nhiên nó không ra cái bảng như hướng dẫn ạ, em  tiếp tục chạy lênh tiếp ở dưới thì báo lỗi này ạ     conda: command not found
![Screenshot from 2024-06-23 13-53-21](https://github.com/UeenHuynh/MGMA_2024/assets/170336899/f2ff0c30-51c7-429b-9dd6-9fda00dfc4e6)

**Comment by lucianhu** [comment]
Chào em, em có thể nêu rõ từng bước 1 cách cụ thể và từng câu lệnh em đã cài đặt conda được không? Chị thấy là em gặp khá nhiều rắc rồi về việc cài đặt tools, em xem lại và học lại các command line cơ bản trong linux, nếu có gì thắc mắc không hiểu hãy chủ động sử dụng chatGPT hay các AI khác để tự chủ động tìm câu trả lời. Việc chủ động tự tìm câu trả lời sẽ giúp em học chủ động và ghi nhớ hơn. Hãy trình bày với anh chị với các cách mà em tìm được thì mọi người có thể hỗ trợ sâu hơn giúp em. Ngoài ra, về conda, đây là 1 môi trường rất tốt và dễ để cài các bioinformatic tools hơn là cài tay (manual thông thường)
https://www.youtube.com/watch?v=2bXGm0ZnJ38&t=315s

**Comment by VanChungCC** [comment]
Dạ em cảm ơn chị ạ.
