### ISSUE TITLE
Hỏi về các tải file powerpoint trên google doc liên kết với Github

### ISSUE THREAD

**Issue by DrYong1996** [UeenHuynh/MGMA_2024#37]
Cho mình hỏi cách tải file power point bài giảng trên google doc: sau khi nhấp vào phần PPTX trên github thì sẽ dẫn đến 1 trang google doc của power point nhưng chỉ đọc chứ không thấy tải về thế nào. Thầy và các bạn giúp em với ạ. Xin cảm ơn.

**Comment by huyha1314** [comment]
![image](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/2e03e292-c2f9-4dd5-8f9b-2252076ed659)
![image](https://github.com/UeenHuynh/MGMA_2024/assets/161665260/b58a23d5-cdbe-4d01-8c45-ae9bf8654672)
Chào bạn nếu bạn muốn down file ppt hoặc pdf về góc phải màn hình có nút down.
Hoặc trong issue 7 #7 có hướng dẫn down cả folder về trên github

**Comment by DrYong1996** [comment]
Cảm ơn bạn nhé

**Comment by DrYong1996** [comment]
Nhưng mà lecture 9,10, mình không thấy file PPT để dowload mà chỉ hiện trên đây mà nhấp vào thì không biết dowload như thế nào. Bạn @huyha1314 hỗ trợ mình với ạ.
![image](https://github.com/UeenHuynh/MGMA_2024/assets/170739225/4ab4fe66-0e7e-4d2b-a135-6685e6e11cd7)
![image](https://github.com/UeenHuynh/MGMA_2024/assets/170739225/55f4973e-32e1-4c5b-9c8d-43a24c948a0e)
![Uploading image.png…]()

**Comment by Khaingyn** [comment]
@ducminhnguyenle nhờ anh up lại link docs mấy bài giảng của anh ạ, em cũng không biết tải thế nào

**Comment by huyha1314** [comment]
Mình đã sửa lại link lecture 10 rồi
