### ISSUE TITLE
Help !!! lỗi khi chạy pgap (NCBI Prokaryotic Genome Annotation Pipeline) 

### ISSUE THREAD

**Issue by TranTrongTin95** [UeenHuynh/MGMA_2024#38]
em có thử chạy pgap cho anotation, kết quả bị lỗi và không tìm được lý do

Đầu tiên em cài đặt docker, và kiểm tra sau khi cài đặt bằng command:

          docker run hello-world

Kết quả:
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

Sau đó chạy pgap như hướng dẫn trong wiki của pgap (https://github.com/ncbi/pgap/wiki/Quick-Start), command line em sử dụng:

          curl -OL https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py

          chmod +x pgap.py

          ./pgap.py --update # required files are downloaded and extracted

          ./pgap.py -r -o test -g ESCO_001_93008360_contigs.fasta -s 'Escherichia coli'

Sau khi run lệnh, trên terminal hiển thị:
PGAP version 2024-04-27.build7426 is up to date.
Output will be placed in: /home/trongtin/bioinformatics/CDC_Project/CRE_research/220624_analysis/pgap/test

Sau  khoảng 5p thì trên terminal thông báo failed và không đưa ra lý do gì cả. Mong được các anh/ chị hỗ trợ ạ

[cwltool.log](https://github.com/user-attachments/files/16030869/cwltool.log)

**Comment by ducminhnguyenle** [comment]
Unfortunately PGAP is not mentioned in the lecture. Based on your description, there is no log file or any details related to your error. Therefore, it is quite impossible to debug.
Please have a look carefully into the documentation of the tool and any dependencies required. Thank you.
