### ISSUE TITLE
[BUG] Lecture 2, homework part 2, SRR25653406.fasta.tar.gz is not gzip format

### ISSUE THREAD

**Issue by ducminhnguyenle** [UeenHuynh/MGMA_2024#39]
`https://github.com/UeenHuynh/MGMA_2024/blob/main/lecture_2/2.%20basic%20Linux%20commands%20part%202/SRR25653406.fasta.tar.gz`
After downloading, the file is not in `gzip` format. It was unable to decompress.
Please have a look and fix ASAP.
Also please have a look at homework part2 pdf fle: `https://github.com/UeenHuynh/MGMA_2024/blob/main/lecture_2/2.%20basic%20Linux%20commands%20part%202/Homework_basic_Linux_commands_part2.pdf`, The URL for this fasta is not correct. I was not able to download the fasta.
Please double check both errors mentioned above.
Thank you.

**Comment by huyha1314** [comment]
Em đã fix lại mấy cái lỗi

**Comment by ducminhnguyenle** [comment]
The download fasta link is working properly now. Thank you @huyha1314.
