### ISSUE TITLE
Hỏi về vị trí của các "option"

### ISSUE THREAD

**Issue by HeCTorTRoNg** [UeenHuynh/MGMA_2024#4]
Trong một câu lệnh thì liệu vị trí của các dòng option có làm ảnh hưởng đến hiệu quả hay chức năng của câu lệnh?
Ví dụ: 
Giả sử câu lệnh tar, chúng ta có các option như sau:
+ -c --create
+ -z, --gzip
+ -f or --file
+ -v or --verbose
thì khi viết chung "-c -v -z -f" có thể viết thành "cvzf"
như vậy nếu ta viết dưới dạng như "czvf", "vczf",...
Liệu câu lệnh có còn thực hiện được chức năng compress và decompres ?

**Comment by huyha1314** [comment]
Trong câu lệnh mỗi option đều có chức năng riêng và điều kiện kèm theo 
ví dụ tar:
+ -f thì sau đó phải là tên file thì mới thõa mãn điều kiện  (-f file.tar..zip)  nên câu lệnh để nén là tar -czvf file.tar..zip  (f phải để cuối) để sau đó là tên file
+ Còn với -v hoặc -z thì không cần xem xét đến thứ tự vì nó không có điều kiện kèm theo

Thì đối với các option mà không cần có điều kiện hay yếu tố khác kèm theo thì vị trí của nó không quan trọng.  Và đặc biệt mình có thể thử các câu lệnh xem nó có thể chạy không. Cứ thử nó trên terminal hoặc hỏi trên chatGPT để có câu trả lời nhanh nhất

**Comment by Khaingyn** [comment]
Theo hiểu biết của em.
- Ở mỗi loại lệnh, có lệnh thì buộc các option phải theo 1 thứ tự nào đó theo hướng dẫn dùng lệnh, có lệnh thì có thể viết lộn xộn option, có lệnh khi dùng nhiều option có thể ghi dính liền các option - có lệnh thì phải ghi tách. Hỏi cụ thể lệnh nào cho từng trường hợp thì em thực sự không nhớ. Cái này dựa trên kinh nghiệm. Chia sẻ về cá nhân em, cái ngày mà em mới bắt đầu học gõ lệnh, thì cách dễ nhất để biết thứ tự option như thế nào, thì em hay gõ bắt trước theo video của người khác, bắt trước theo các tài liệu tham khảo, youtube, web,.v.v... và khi mà em nghĩ tới muốn biết xem vị trí khác có được không thì em thử luôn bằng cách gõ trên terminal xem kết quả ra như thế nào. Kết quả của lệnh sẽ có: thực hiện được hay không thực hiện được (kèm theo thông báo lỗi nào đó), vì mỗi lệnh được nhà phát triển đặt cho nó theo cú pháp (syntax) nào đó, nên khi mình nhập không đúng cú pháp, thì lệnh không thực hiện được cũng là chuyện dễ hiểu.
- Trước tiên anh/chị cần làm rõ lại các option trong lệnh tar nha, giả sử nếu như dùng 4 cái option ở trên thì là mình đang compress (nén), chứ không decompress (giải nén) được. 
- Khi nén với tar, 2 option -c và -f là buộc phải có khi dùng tar; khi mà chỉ dùng 2 option này, thì tar chỉ đang tạo file lưu trữ (archive), nôm na là gom tất cả file và thư mục được chỉ định thành 1 "file". Nhưng mà cái mục đích nén file chính là để giảm kích thước file, chính vì thế nếu chỉ dùng 2 option trên thì chưa đạt được mục đích của việc "nén file". Nên ở đây em sử dụng thêm option -z để dùng gzip để nén file lưu trữ này thành 1 file nén có định dạng gzip, 1 định dạng nén phổ biển trong linux. Tar nó cũng hỗ trợ nhiều định dạng nén khác, anh/chị có thể tham khảo bài này để rõ hơn (https://hocdevops.com/commands/lenh-tar-trong-linux-tao-va-giai-nen-cac-file-nen/). Còn option -v để chỉ định tar in ra terminal quá trình nén, nếu không có thì tar vẫn nén được file.
- Em bổ sung thêm, khi tạo file lưu trữ thôi thì mình đặt tên file có đuôi .tar, còn khi mình dùng option nào đó để file được nén theo định dạng nào đó mà tar hỗ trợ, chẳng hạn như ở trên em dùng gzip, thì mình đặt tên file có đuôi .tar.gz hoặc .tgz
- Khi giải nén với tar, thì 2 option buộc phải có là -x và -f.
- Tương tự như ý đầu, em có thể tự thử các vị trí option khác nhau như thế nào bằng cách gõ thử trong terminal, anh/chị xem hình dưới đây:
![image](https://github.com/UeenHuynh/MGMA_2024/assets/147164871/db1c41b8-1a48-4ed1-b806-0f7e25208a42)

Em thông tin đến anh/chị.

**Comment by Khaingyn** [comment]
Ngoài ra, comment này chung cho mọi người, mọi người tự tìm hiểu thêm lệnh gzip và gunzip, tại vì sẽ có trường hợp người ta không dùng tar để tạo file lưu trữ và nén với gzip (đuôi .tar.gz) mà người ta dùng gzip để nén luôn (đối với đối tượng muốn nén là file) thì file sẽ có đuôi .gz thôi chứ không có .tar phía trước .gz, trong trường hợp này, để giải nén, mình sẽ sử dụng lệnh "gzip" với option -d, hoặc lệnh "gunzip".
