### ISSUE TITLE
Hướng dẫn Tải package "Phyloseq" trên Rstudio

### ISSUE THREAD

**Issue by ONT16S** [UeenHuynh/MGMA_2024#40]
Chào mọi người, mình mới tải xong gói "Phyloseq" cho Rstudio nếu anh/chị nào bị kẹt ở phần tải do không vào được link như trên web Phyloseq yêu cầu thì có thể không vào đường link nên có thể dùng các sau:
![image](https://github.com/UeenHuynh/MGMA_2024/assets/171407091/16259fa9-2cb1-41b6-bf81-7670a9e77b37)

# Step 1: Kiểm tra xem có BiocManager nếu không thì sẽ tải bói này 
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
![image](https://github.com/UeenHuynh/MGMA_2024/assets/171407091/897159d6-91fc-44e6-821e-45222d730864)

# Step 2: Khi cài xong gói "Biomanager" thì có thể tải "phyloseq"
BiocManager::install("phyloseq")
![image](https://github.com/UeenHuynh/MGMA_2024/assets/171407091/0fb208da-7440-42ca-a858-d26612988c0e)
![image](https://github.com/UeenHuynh/MGMA_2024/assets/171407091/e27032be-9979-436d-96e0-3d3e0919bf54)

# Step 3: Kiểm tra gói "phyloseq" 
packageVersion('phyloseq')
![image](https://github.com/UeenHuynh/MGMA_2024/assets/171407091/7731e20f-ecdd-4cba-910f-e68ca8b42923)

library(phyloseq)
installed.packages()["phyloseq", ] 
![image](https://github.com/UeenHuynh/MGMA_2024/assets/171407091/46f5d646-0e55-4b53-971d-fbcbd9d42612)

**Comment by huyha1314** [comment]
Cảm ơn thông tin hữu ích đến từ bạn. https://joey711.github.io/phyloseq/install.html - Đường link thêm để mọi người có thể xem cách cài khác
