### ISSUE TITLE
Hệ điều hành Ubuntu bị lỗi ?

### ISSUE THREAD

**Issue by ManhHungvozer** [UeenHuynh/MGMA_2024#42]
Mình đang sử dụng máy bình thường thì máy có dấu hiệu đơ rồi chậm hẳn, sau đó đứng máy. Sau đó mình tắt máy nóng và khởi động lại thì máy không lên và chỉ hiện ra hình như dưới. Mong các anh chị và các bạn nếu ai biết thì chỉ mình vì tối nay mình có báo cáo project mà giờ máy lại không thể sử dụng được. Cảm ơn mọi người nhiều![IMG_20240811_152548_674.jpg](https://github.com/user-attachments/assets/a487a499-4c38-45c0-bb34-508a432b6f02)

**Comment by ONT16S** [comment]
Hello anh, em search thì cái này do nhiều lý do anh xem thử rồi loại trừ ra nhé:
1. Gắn SSD vào máy khác nếu có để check thử
2. Kiểm tra dây kết nối của SSD và máy (thay dây hoặc đổi port cắm)
3. Cập nhật lại hệ thống (có khi nó bình thuờng lại)
4.Lỗi driver (fsck để check) hoặc bios (vào setting bios)
5. Lỗi nguồn (không đủ điện nên ổ tắt)

**Comment by ManhHungvozer** [comment]
Mình sẽ thử làm theo cách cách trên, cảm ơn sự hỗ trợ của bạn nhiều nhé!
