### ISSUE TITLE
!bash Miniforge3-Linux-x86_64.sh

### ISSUE THREAD

**Issue by phgiang11** [UeenHuynh/MGMA_2024#44]
dạ, mình thực thi lệnh trên colab, lệnh này mình chờ gần 10 phút hơn là bình thường không ạ, nhờ anh chị hướng dẫn giúp như colab mình đang làm. Xin cảm ơn! 
https://colab.research.google.com/drive/1miyOpE4Ns0KfX7czpYyn6W1wKZacjbKe#scrollTo=MmYGOZ6DD-Hg

**Comment by lucianhu** [comment]
Chào bạn, trong` Colab`, việc cài `conda` nó khác với chạy trên máy local, bạn thử cái code này nhé
```
# Install condacolab package to enable conda usage within Google Colab
# Condacolab facilitates the installation and management of conda environments in Colab

# Install the condacolab package
!pip install condacolab

# Import the condacolab module to use its functionalities
import condacolab

# Install conda and initialize it within the Colab environment
# This step sets up the conda environment for subsequent package management
condacolab.install()
```

```
# Create a new conda environment and install tools
%%bash
# Create a new environment called 'longread'
mamba create -y -n longread python=3.8

# Activate the environment
source activate longread

# Install necessary tools using mamba
mamba install -y -c bioconda minimap2 samtools kraken2 bracken sra-tools.......

# Confirm installations
echo "Setup complete."
```

Tuy nhiên, các bước từ xử lý file tới binning, thì được khuyến khích chạy trên máy local, vì tốc độ xử lý và thời gian chạy sẽ mất 1 ngày hơn. 

Thân,

**Comment by phgiang11** [comment]
Cảm ơn Như,hôm qua mình cũng thử trên máy local ,bước này qua cũng nhanh
nhưng bước mamba long_read mình bị đứng máy luôn vì quá tải phải reset lai
toàn bộ ổ cứng, có thể bạn chia sẻ giúp mình hướng dẫn tự cài một máy ảo có
ubuntu chạy được terminal trong đó với,mình xem video bài khóa trước có đề
cập tới

Cảm ơn bạn nhiều

Hà Giang

Vào 14:52 T.3, 15 Th10, 2024 Quynh Nhu Nguyen ***@***.***> đã
viết:

**Comment by lucianhu** [comment]
Bên mình không khuyến khích cài máy ảo chạy được ubuntu vì nó sẽ rất dễ xung đột với các tools. Bạn có thể tham khảo các website, youtube khác hoặc hỏi AI họ sẽ hướng dẫn kỹ càng hơn nếu bạn có nhu cầu tạo máy ảo,

**Comment by phgiang11** [comment]
Chào Như, 
chị xử lý ubuntu trên VMbox đến bước minimap2 trên long_read thì máy align với hg38 không nổi, command của mình vầy 

minimap2 -t 4 -ax map-ont --secondary=no hg38.fa trimmed_long/trimmed_SRR18491202.fastplong.gz -o trimmed_SRR18491202.fastplong_hg38_sam
nếu được nhờ Như gửi cho mình file data họ đã map giùm (file sam và bam ) luôn với . để mình thực hành các phần sau.
Cảm ơn Như
HGiang

**Comment by lucianhu** [comment]
Chào chị, 

Những bước xử lý sau cần cấu hình mạnh hơn nữa ạ. Chỉ có bước thống kê thì mới cần ít tài nguyên máy thôi ạ.

Nếu máy chị không đủ mạnh, chị thực tập mỗi bước vẽ hình và thống kê dữ liệu [Google Colab Notebook](https://colab.research.google.com/drive/1Eh_krhVULtoJDzIgnJOKZK5PITiNYYRU?usp=sharing#scrollTo=JZ74yuFaZJUy) và lấy file gốc từ đây [GitHub - Raw Kraken Bracken Output](https://github.com/UeenHuynh/MGMA_2024/tree/main/lecture_26/Results/Raw_kraken_bracken_output).

Ngoài ra, chị có thể thử với mẫu nhẹ hơn như SRR15902152 : https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP337148&o=acc_s%3Aa

Thân,

Như

**Comment by phgiang11** [comment]
cảm ơn Như, 
Cho chị hỏi ý nghĩa bước Bowtie file hg38.fa để làm gì, chị có kraken2 file short read dùng file unmapped để chạy thì không định danh ra chủng nào, khi dùng file raw mẫu short read chạy kraken2 thì máy load được 320MB rồi tự tắt terminal, hiện tại không hỏng gì nhưng quá trình định danh với file fa.gz cũng không hoàn thành. Có thể giải thích cho chị được không em , hihi

**Comment by lucianhu** [comment]
Chào chị,
Bước Bowtie file hg38.fa là để lọc ra và bỏ đi vật chủ. Ví dụ của mình là mẫu phân người, vật chủ là người thì phải loại bỏ đi gene của người. Trong mẫu phân, hơn 90% là DNA của người, nên phải loại bỏ đi thì mình mới phát hiện được 1 phần nhỏ các vi sinh vật ở người. Còn nếu chị chạy mẫu plant metagenome như em đưa, thì chị thử bỏ qua bước loại thể vật chủ, chỉ cần cắt adapter và tiếp tục tới bước định danh và xây dựng contigs.
Thân,
Như

**Comment by phgiang11** [comment]
À tại mình nói hông rõ, mình muốn hỏi là tạo ra bt2_index_base để làm gì
vậy em

Vào 15:57 T.5, 31 Th10, 2024 Quynh Nhu Nguyen ***@***.***> đã
viết:

**Comment by lucianhu** [comment]
Chào chị,

`bt2_index_base` thường được dùng để tạo chỉ mục (index) cho bộ gen tham chiếu hoặc dữ liệu chuỗi gen trong Bowtie2. Bước lập chỉ mục này rất quan trọng vì nó giúp Bowtie2 tìm kiếm các vị trí trùng khớp trong bộ gen nhanh hơn trong quá trình căn chỉnh. Bằng cách tạo chỉ mục, Bowtie2 có thể tìm kiếm và căn chỉnh chuỗi hiệu quả hơn, giúp tăng tốc độ và độ chính xác của quá trình căn chỉnh.

Thân,

Như

**Comment by phgiang11** [comment]
Cảm ơn nha Như ơi

Vào 20:52 T.6, 1 Th11, 2024 Quynh Nhu Nguyen ***@***.***> đã
viết:
