### ISSUE TITLE
mamba create --name binning python=2.7.15 \     metawrap \     biopython=1.68 \     blast=2.6.0 \.....

### ISSUE THREAD

**Issue by phgiang11** [UeenHuynh/MGMA_2024#45]
bên mình báo các package incompatible ,và package nào có số phía sau là báo "does not exits". Nhờ bạn giúp dùm. Thân

**Comment by lucianhu** [comment]
Chào bạn, mình vừa test lại thì không bị lỗi gì cả. Bạn thử chụp màn hình lên xem. 

Ngoài ra bạn thử kiểm tra lại trong phần `mamba ` có channel `bioconda` chưa, nếu chưa thì cài vào:

```
mamba config --show channels
mamba config --add channels bioconda
```

Ngoài ra, các bước từ fastqc, assembly, taxonomy bạn đã chạy được chưa?
```
mamba create --name binning python=2.7.15 \
    metawrap \
    biopython=1.68 \
    blast=2.6.0 \
    bmtagger=3.101 \
    bowtie2=2.3.5 \
    bwa=0.7.17 \
    checkm-genome=1.0.12 \
    fastqc=0.11.8 \
    kraken=1.1 \
    kraken2=2.0 \
    krona=2.7 \
    matplotlib-base=2.2.3 \
    maxbin2=2.2.6 \
    metabat2=2.12.1 \
    pandas=0.24.2 \
    perl-bioperl \
    pplacer=1.1.alpha19 \
    prokka=1 \
    quast=5.0.2 \
    r-ggplot2=3.1.0 \
    r-reshape2 \
    r-recommended=3.5.1 \
    samtools=1.9 \
    seaborn=0.9.0 \
    spades=3.13.0 \
    trim-galore=0.5.0
```

**Comment by phgiang11** [comment]
à ok, chị có cài lại các tools này được rồi, cảm ơn em

**Comment by phgiang11** [comment]
vì sao bên em chọn confidence là 0.03? Mẫu short read sau khi host remove  bằng bowtie có loại 100% dna của host có trong mẫu không vì theo bên mình xử lý vẫn còn host
![SRR18491279   CD_7_short_](https://github.com/user-attachments/assets/eba3e208-25d8-4ab1-9d28-e04b468b002e)
![SRR18491279   CD_7_short_unmapped ](https://github.com/user-attachments/assets/17a04232-a935-4bf5-b3c8-6733820db998)

**Comment by lucianhu** [comment]
Chào chị,

1. Về việc chọn Kraken 2 với confidence 0.03: Giá trị confidence 0.03 như em là khá thấp và không phải là lựa chọn tối ưu. Thông thường, người ta khuyến nghị sử dụng confidence từ 0.1 đến 0.5 tùy theo mục đích nghiên cứu.

Chị tham khảo ở đây nhé https://github.com/DerrickWood/kraken2/issues/265

Sau khi chạy kraken, để ý % độ classification. Nếu trên 50%, thì có thể tiếp tục các bước phân sau. Nếu không, thì phải điều chỉnh xuống. VD, với mẫu đất, 60M reads x 2 với Kraken-nt db (233.3GB) thì nhóm em lấy confidence có 0.01.

2. Về vấn đề DNA host sau khi remove bằng Bowtie:
- Bowtie không loại bỏ 100% DNA của host
- Thường còn khoảng 1-10% DNA host còn sót lại

Thân mến,

Như

**Comment by phgiang11** [comment]
Chào Như
Ui, nhiều thông tin bổ ích quá, chị cảm ơn em nhiều nhiều nhé ☺️

Vào 21:16 T.6, 1 Th11, 2024 Quynh Nhu Nguyen ***@***.***> đã
viết:
