### ISSUE TITLE
[Khải] Lưu ý về bài tập Basic Linux Commands part 2 

### ISSUE THREAD

**Issue by Khaingyn** [UeenHuynh/MGMA_2024#5]
Mọi người chú ý cái link mà em để trong bài tập, giờ em mới phát hiện ra, xin lỗi mọi người. Do file bài tập em tải lên github là file pdf, nên khi mọi người copy link đó từ pdf vào terminal để dùng wget tải file về, thì link đó nó sẽ bị bẻ làm 2 hàng y chang như trong pdf, nên mọi người dùng phím di chuyển trái phải để di chuyển con trỏ nhấp nháy, di chuyển nó tới chữ "a" của hàng 2 của link, và xoá tiến lên 1 cái bằng phía backspace để nối chữ "a" đó vào đứng kế với chữ "m" hàng 1 của link. Do lúc em chuẩn bị bài là file word, nên khi copy sẽ không bị vấn đề này, nên em không để ý tới, còn để pdf thì bị. Mọi người xem thêm cllip em quay lại màn hình, trong link google drive, để dễ hiểu hơn: https://drive.google.com/file/d/1rtKz1LJXr9KJSwkVuZK6pF1hh2prVjwm/view?usp=sharing

**Comment by Hoabio** [comment]
Anh Khải cho em hỏi. Em thấy khi viết commands line, nó có 1 quy tắc chung k thay đổi. Mình có thể viết sẳn các lệnh đó ra sẳn Khi nào mình dùng công cụ nào để xử lý gen thì mình chỉ cần coppy past dc k anh. Kiểu mình có 1 thuật toán mẫu cho xữ lý công cụ đó. Ví dụ: như mình cần công cụ cắt và lắp ráp gen, sau đó gắn gen  lại ... Em thấy như vậy sẽ nhanh hơn với mình k cần phải nhớ các lệnh nhỏ nhỏ.

**Comment by Khaingyn** [comment]
> Anh Khải cho em hỏi. Em thấy khi viết commands line, nó có 1 quy tắc chung k thay đổi. Mình có thể viết sẳn các lệnh đó ra sẳn Khi nào mình dùng công cụ nào để xử lý gen thì mình chỉ cần coppy past dc k anh. Kiểu mình có 1 thuật toán mẫu cho xữ lý công cụ đó. Ví dụ: như mình cần công cụ cắt và lắp ráp gen, sau đó gắn gen lại ... Em thấy như vậy sẽ nhanh hơn với mình k cần phải nhớ các lệnh nhỏ nhỏ.

Phần chị đang nói chính là 1 trong các mục đích của việc viết các lệnh vào 1 file văn bản, file này là gọi là file script, và các lệnh này được thực thi bởi bash nên gọi cụ thể hơn file này là file bash script; cũng nằm trong 2 bài bash script trong 2 buổi vừa qua của Khoá học.

**Comment by ducminhnguyenle** [comment]
Nếu issue này đã được giải quyết, mình sẽ close issue này lại.
