### ISSUE TITLE
Hỏi về lỗi khi sử dụng function trong bash script

### ISSUE THREAD

**Issue by HeCTorTRoNg** [UeenHuynh/MGMA_2024#6]
Khi sử dụng lệnh function trong bash script thì mình bị lỗi "command not found" ở terminal.
Mình đã cố thử nhiều format khác của lệnh như sau: 

![Screenshot 2024-05-25 092917](https://github.com/UeenHuynh/MGMA_2024/assets/170555937/71a4cf4f-a9af-4f50-a5cf-acfc4cebcfe1)

Nhưng vẫn bị dính lỗi "command not found", cụ thể như sau:
+ terminal:
![image](https://github.com/UeenHuynh/MGMA_2024/assets/170555937/230224b8-58b7-4625-8749-e495d89d7274)
 
+Bash script:
![image](https://github.com/UeenHuynh/MGMA_2024/assets/170555937/7e0fbdf4-bba1-4e40-816d-29d29109bd92)

Mình nên giải quyết trường hợp này như thế nào?
Cảm ơn.

**Comment by huyha1314** [comment]
Bạn phải thực thi(chạy) file bash script trước rồi mới sử dụng function được.

**Comment by huyha1314** [comment]
Và mỗi lần tắt máy hay tắt terminal thì mình đều phải chạy lại file script. Vì nó kh lưu trữ trong bộ nhớ dài hạn của hệ điều hành
