### ISSUE TITLE
Phần bài tập basic Linux commands

### ISSUE THREAD

**Issue by VanChungCC** [UeenHuynh/MGMA_2024#8]
Dạ cho em hỏi là sao cái link này
https://github.com/UeenHuynh/MGMA_2024/raw/main/lecture2/2.%20basic%20Linux%20comm
ands%20part%202/SRR25653406.fasta.tar.gz 
em dùng lệnh wget https://github.com/UeenHuynh/MGMA_2024/raw/main/lecture2/2.%20basic%20Linux%20comm
ands%20part%202/SRR25653406.fasta.tar.gz
để tải về nhưng máy trả về là 
-2024-05-26 19:10:50--  https://github.com/UeenHuynh/MGMA_2024/raw/main/lecture2/2.%20basic%20Linux%20comm
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-26 19:10:51 ERROR 404: Not Found.

bash: ands%20part%202/SRR25653406.fasta.tar.gz: No such file or directory
Em vào kiểm tra có file đó chưa thì chưa thấy ạ, có ai bị như em không ạ, và cách giải quyết ra sao ạ.
Em cảm ơn

**Comment by Khaingyn** [comment]
Vấn đề này em đã đăng thành 1 issue rồi ạ: https://github.com/UeenHuynh/MGMA_2024/issues/5#issue-2315716445

**Comment by VanChungCC** [comment]
Dạ, em cảm ơn ạ.
