### ISSUE TITLE
Hỏi về nội dung khóa học MGMA 2024

### ISSUE THREAD

**Issue by tuanna199** [UeenHuynh/MGMA_2024#9]
Em chào thầy và mọi người ạ. Hiện em đang là sinh viên năm thứ 4 nên em cũng có quan tâm đến thị trường việc làm của ngành tin sinh. Sau khi đọc các mô tả công việc thì em nhận thấy ngoài yêu cầu về sử dụng bash script, ubuntu, R ra thì họ còn có yêu cầu về việc ứng viên có kinh nghiệm với cloud, high-performace computing cũng như workflow management system như nextflow/snakemake. Em có câu hỏi là không biết các phần nội dung này có được dạy trong khóa học này hay không ạ, hoặc là thầy có dự định mở lớp về các chủ đề này không ạ, một phần vì em cũng thấy các chủ đề này khá là nâng cao nặng về bên kỹ thuật nhiều hơn, cũng khá khó để có thể tự học ạ. Em cảm ơn thầy ạ.

**Comment by luuloi** [comment]
Chào Tuanna199, 
Cảm ơn câu hỏi rất hay của em. Tôi đã có dự tính dạy những khóa này và đã xây dựng nội dung, chuẩn bị gần xong giáo trình rồi, phần này phải thực tập trên cloud hay HPC khá nhiều. Do vậy, chúng tôi đang cố gắng tìm nhà tài trợ cho phần thuê cloud và HPC để có thể dạy miễn phí cho các bạn được. Bạn cố gắng chờ thêm nhé! Nếu bạn tìm được nhà tài trợ thì giới thiệu cho tôi nhé em! Sẽ là công đức vô lượng em nhé! Cảm ơn em lần nữa!!!

**Comment by tuanna199** [comment]
Dạ, nếu vậy thì tuyệt quá ạ.

**Comment by Hoabio** [comment]
Thầy cho em hỏi, trong quá trình phân tích hệ gen vi khuẩn, nếu xuất hiện gen nhãy (Transposable Elements) thì có ảnh hưởng đến quá trình lắp ráp và phân tích không thầy ạ.
Em cảm ơn Thầy và mn nhiều ạ
